config/routes.rb
Rails.application.routes.draw do

  get 'home/show'
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'
  get 'donor_home', to: "donors#donor_home", as: "donor_interface"
  get 'highest_donor', to: "donors#highest_donor", as: "highest_donor"



  resources :sessions, only: [:new, :create, :destroy]
  resource :home, only: [:show]
  root to: "home#show"

  resources :donors, only: [:new, :create]
  resources :recipients


  resources :categories do
    resources :recipients 
  end

  get "/total_user_donations", to: "categories#total_user_donation", as: "categories/total_user_donation"
  get "/recipients/:id/next", to: "recipients#next"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/donor.rb
class Donor < ApplicationRecord
	has_secure_password

  validates :email, presence: true
  validates :email, uniqueness: true
  validates :password, presence: true
  validates :password, confirmation: true


	has_many :recipients
	has_many :categories, through: :recipients

  def self.highest_donor
    Donor.joins(:categories)
      .select("donors.*, 
        count(categories.toilet_paper) as first_count,
        count(categories.dental_hygiene) as second_count,
        count(categories.first_aid) as third_count,
        count(categories.general_hygiene) as fourth_count,
        count(categories.underwear_socks) as fifth_count,
        count(categories.blankets) as sixth_count,
        count(categories.school_supplies) as seventh_count,
        count(categories.diapers) as eighth_count"
        )
      .group("donors.id")
      .order("first_count DESC, second_count DESC, third_count DESC,
        fourth_count DESC, fifth_count DESC, sixth_count DESC, seventh_count DESC,
        eighth_count DESC")
  end 

 def self.find_or_create_by_omniauth(auth_hash)
    self.where(email: auth_hash["info"]["email"]).first_or_create do |donor|
      donor.password = SecureRandom.hex
    end
  end 
end


#This returns the person with the most donations (not counted)
#def self.highest_donor
    #Donor.joins(:categories)
      #.select("donors.*, count(donors.id) as dcount")
      #.group("donors.id")
      #.order("dcount DESC")
  #end 

app/controllers/donors_controller.rb
class DonorsController < ApplicationController	
	
	def donor_home
		@categories = Category.all
		@total_website_donations = Category.total_donations
	end

	def highest_donor
		@highest = Donor.highest_donor
	end 


	def new
		@donor = Donor.new
	end

	def create
		@donor = Donor.new(donor_params)
		if @donor.save
			session[:user_id] = @donor.id
			redirect_to donor_interface_path
		else
			render :new
		end
	end

	private 
	
	def donor_params
		params.require(:donor).permit(:email, :password, :password_confirmation)
	end
end

app/helpers/donors_helper.rb
module DonorsHelper
end

app/views/donors/_form.html.erb
<h2>Signup</h2>

<% if @donor.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@donor.errors.count, "error") %></h2>

    <ul>
    <% @donor.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_for @donor do |f| %>
  <%= f.label :email %><br>
  <%= f.text_field :email%><br>
  <%= f.label :password %><br>
  <%= f.password_field :password, placeholder: "(hidden)" %><br>
  <%= f.label :password_confirmation %><br>
  <%= f.password_field :password_confirmation, placeholder: "(hidden)" %><br><br><Br>
  <%= f.submit %><br><br>
<% end %>

<%= link_to "Back to Home Page", home_show_path %>

app/views/donors/donor_home.html.erb
<% if alert %>
  <h1><p class="alert-danger"><%= flash[:alert] %></p></h1>
<% end %>

<h2> Welcome to your Donor Interface, <%= current_user.email %>!</h2>
<%= link_to "Donate Here", new_category_path(@category) %><br><br>
<%= link_to "Your Total Donations", categories_total_user_donation_path %><br><br>
<%= link_to "Highest Donor", highest_donor_path %>
<br>
<br>
<html>
<head>
<style>
table, th, td {
    border: 1px solid black;
    border-collapse: collapse;
    table-layout:fixed;
}
th, td {
    padding: 5px;
    text-align: left;
}
</style>
</head>
<body>
<h2>Your Recipient List</h2>
<p>To update or delete a recipient, just click on the their first name!</p>
<% current_user.recipients.each do |recipient| %>
<table style="width:100%">
  <tr>
    <th>First Name:</th>
    <td><%= link_to recipient.first_name, category_recipient_path(recipient.category, recipient) %></td>
  </tr>
  <tr>
    <th>Last Name:</th>
    <td><%= recipient.last_name %></td>
  </tr>
  <tr>
    <th>Location</th>
    <td><%= recipient.location %></td>
  </tr>
  <tr>
    <th>Gender</th>
    <td><%= recipient.gender %></td>
  </tr>
  <tr>
    <th>Personal_notes</th>
    <td><%= recipient.personal_notes %></td>
  </table>
  <% end %>
</table>
</body>
</html>
<br>
<br>
<h2>Website Donation Tracker By Category!</h2>
	<table style="width:100%">
  <tr>
    <th>Toilet Paper</th>
    <th>Diapers</th>
    <th>Dental Hygiene</th>
    <th>First Aid</th>
    <th>General Hygiene</th>
    <th>Underwear and Socks</th>
    <th>Blankets</th>
    <th>School Supplies</th>
  </tr>
  <tr>
  	<td>$<%= @categories.toilet_paper_totals %></td>
  	<td>$<%= @categories.diaper_totals %></td>
  	<td>$<%= @categories.dental_hygiene_totals %></td>
  	<td>$<%= @categories.first_aid_totals %></td>
  	<td>$<%= @categories.general_hygiene_totals %></td>
  	<td>$<%= @categories.underwear_socks_totals %></td>
  	<td>$<%= @categories.blankets_totals %></td>
  	<td>$<%= @categories.school_supplies_totals %></td>
</table>
<br>
<br>
<h2>Website Donation Tracker!</h2>
<table>
<tr>
<td>
$<%= @total_website_donations %></td>
</tr>
</table>
<br>
<br>
<br>
<br>

app/views/donors/highest_donor.html.erb
<% @highest.each_with_index do |donor, i| %>
<%= i + 1 %>.
<%= donor.email %><br><br>
<% end %>

app/views/donors/new.html.erb
<%= render 'form' %>