config/routes.rb
Rails.application.routes.draw do

  get 'home/show'
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'
  get 'donor_home', to: "donors#donor_home", as: "donor_interface"
  get 'highest_donor', to: "donors#highest_donor", as: "highest_donor"



  resources :sessions, only: [:new, :create, :destroy]
  resource :home, only: [:show]
  root to: "home#show"

  resources :donors, only: [:new, :create]
  resources :recipients


  resources :categories do
    resources :recipients 
  end

  get "/total_user_donations", to: "categories#total_user_donation", as: "categories/total_user_donation"
  get "/recipients/:id/next", to: "recipients#next"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/recipient.rb
class Recipient < ApplicationRecord
	belongs_to :donor
	belongs_to :category, dependent: :destroy

	validates :first_name, :last_name, :location, :gender, presence: true

	before_destroy do 
		@category = self.category
	end

	after_destroy do 
		unless @category.recipients.any?
			@category.destroy
		end
	end

	def next_recipient
		donor = self.donor
		next_recipient = Recipient.where("id > ? AND donor_id = ?", id, donor.id).first
		reset_count = Recipient.where("donor_id = ?", donor.id).first
		next_recipient ? next_recipient : reset_count
	end

end

app/controllers/recipients_controller.rb
class RecipientsController < ApplicationController

	before_action :redirect_if_not_logged_in
	before_action :set_recipient, only: [:show, :edit, :update, :destroy]

	def index
		@recipients = current_user.recipients.all
		respond_to do |format|
		format.html {render :show}
		format.json {render json: @recipients}
	  end
	end 

	def show
		@recipient.donor == current_user
		@category = current_user.categories.find_by(params[:category_id])
		@category_grabber = current_user.recipients.find_by(id: params[:id])

		respond_to do |format|
		format.html {render :show}
		format.json {render json: @category_grabber}
	  end
	end

	def next
		@recipient = current_user.recipients.find_by(id: params[:id])
		@next_recipient = @recipient.next_recipient
		render json: @next_recipient
	end

	def create
		@category = Category.find(params[:category_id])
		@recipient = @category.recipients.build(recipient_params)
		@recipient[:donor_id] = current_user.id
		@recipient[:id] = @category.id
		if @recipient.save
			 render json: @recipient, status: 201
		else
			 render :_form
		end
	end

	def edit
		if @recipient.donor == current_user
			render :edit
		else
			redirect_to donor_interface_path, alert: "Error: That was not your recipient! Record not updated!"
		end
	end

	def update
		@category = Category.find(params[:id])
		@recipient = @category.recipients.find(params[:id])
		if @recipient.update(recipient_params)
			redirect_to donor_interface_path
		else
			render :edit
		end
	end

	def destroy
		if @recipient.donor == current_user
		   @recipient.destroy
		    redirect_to donor_interface_path
		else
		    redirect_to donor_interface_path, alert: "Error: That was not your recipient! Record not deleted!"
		end
	end 

	private 

	def recipient_params
		params.require(:recipient).permit(
			:first_name,
			:last_name,
			:location,
			:gender,
			:personal_notes,
			:category_id,
			:donor_id
			)
	end

	def set_recipient
		@recipient = Recipient.find_by(id: params[:id])
	end

end

app/helpers/recipients_helper.rb
module RecipientsHelper
end

app/views/recipients/_form.html.erb
<%= form_for([@category, @recipient]) do |f| %>

<% if @recipient.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@recipient.errors.count, "error") %></h2>

    <ul>
    <% @recipient.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<div class="form-group">
    <%= f.hidden_field :donor_id, class: "form-control" %></div>

<div class="form-group">    
    <%= f.hidden_field :category_id, class: "form-control" %></div>

<div class="form-group">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name, class: "form-control" %></div>

  <div class="form-group">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name, class: "form-control" %></div>

  <div class="form-group">
    <%= f.label :location %><br>
    <%= f.text_field :location, class: "form-control" %></div>

  <div class="form-group">
    <%= f.label :gender %><br>
    <%= f.text_field :gender, class: "form-control" %></div>

  <div class="form-group">
    <%= f.label :personal_notes %><br>
    <%= f.text_area :personal_notes, :cols => "10", :rows => "10", class: "form-control" %></div>

    

<div class="actions">
    <%= f.submit  %>
  </div>
<% end %>
<br>

app/views/recipients/edit.html.erb
<%= form_for([@category, @recipient]) do |f| %>
<%= render 'form', f: f %>

<% end %>

app/views/recipients/show.html.erb
<html>
<head>
<style>
table, th, td {
    border: 1px solid black;
    border-collapse: collapse;
    table-layout:fixed;
}
th, td {
    padding: 5px;
    text-align: left;
}
</style>
</head>
<body>
<h2><%= "#{@recipient.first_name} Personal Info" %></h2>

<table style="width:100%">
	<tr>
		<th>First Name</th>
    	<th>Last Name</th>
    	<th>Location</th>
    	<th>Gender</th>
    	<th>Personal Notes</th>
	</tr>

	<tr>
		<td id="firstName"><%= @recipient.first_name %></td>
		<td id="lastName"><%= @recipient.last_name %></td>
		<td id="location"><%= @recipient.location %></td>
		<td id="gender"><%= @recipient.gender %></td>
		<td id="personalNotes"><%= @recipient.personal_notes %></td>
	</tr>
</table>
<br>
<%= button_to "Edit", edit_category_recipient_path(@recipient.category, @recipient), method: :get %>
<br>
<%= button_to "Delete", category_recipient_path(@recipient.category, @recipient), method: "delete", class: "destroy" %>
<br>
<button class="js-next-recipient" data-id="<%= @recipient.id %>">Next Recipient</button><br><br>

<p>Note: When going through recipients, please remember that you are still on the initial recipients home page.  Thank you!</p>
<br>

<button class="js-show-category" data-id="<%= @category_grabber.id %>">Your Donation to this Recipient</button>
<br>
<br>
<br>

<table id="recipientDonations" style="width:100%">
  <tr>
    <th>Donation Count</th>
    <th>Toilet Paper</th>
    <th>Diapers</th>
    <th>Dental Hygiene</th>
    <th>First Aid</th>
    <th>General Hygiene</th>
    <th>Underwear and Socks</th>
    <th>Blankets</th>
    <th>School Supplies</th>
  </tr>
</table>
<br>
<br>
</body>
</html>