config/routes.rb
Rails.application.routes.draw do

  get 'home/show'
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'
  get 'donor_home', to: "donors#donor_home", as: "donor_interface"
  get 'highest_donor', to: "donors#highest_donor", as: "highest_donor"



  resources :sessions, only: [:new, :create, :destroy]
  resource :home, only: [:show]
  root to: "home#show"

  resources :donors, only: [:new, :create]
  resources :recipients


  resources :categories do
    resources :recipients 
  end

  get "/total_user_donations", to: "categories#total_user_donation", as: "categories/total_user_donation"
  get "/recipients/:id/next", to: "recipients#next"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= yield %>
    <title>Donate by Necessity</title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div>
      <% if current_user %>
        Signed in as <strong><%= current_user.email %></strong>!
        <%= link_to "Sign out", signout_path, id: "sign_out" %><br><br>
        <%= link_to "Back to Your Donor Platform", donor_interface_path %>
        <br>
        <br>
      <% else %>
        <%= link_to "Sign in with Google", "/auth/google_oauth2", id: "sign_in" %>
      <% end %>
    </div>
    <div>
    </div>
  </body>
</html>